[package]
distribution = "2201.0.0"
org= "ballerinax"
name= "googleapis.people"
version= "2.2.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Sales & CRM/Contact Management", "Cost/Free", "Vendor/Google"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.people"

[build-options]
observabilityIncluded = true
